### ISSUE TITLE
Unexpected crash or possible incompatibility

### ISSUE THREAD

**Issue by HoodieRocks** [isXander/AdaptiveTooltips#5]
Hello, when running the mod, my game crashes on startup, below I've provided the logs

AdaptiveTooltips Version is 1.0.1
Fabric 0.14.10-1.19.2
Fabric API version 0.58.5

```

[10:18:37] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.10
[10:18:37] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[10:18:37] [main/INFO]: Loading 140 mods:
	- adaptive-tooltips 1.0.1
	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- antighost 1.19.1-fabric0.58.5-1.1.5
	- appleskin 2.4.0+mc1.19
	- audio_engine_tweaks 1.2.3
	- auditory 0.0.3-1.19.x
	- bebooks 1.4.1
	- bedrockify 1.4.2+mc1.19.1
	- better-dark-mode 2.1.0
	- betterstats 2.0
	- betterthirdperson 1.8.1
	- bobby 4.0.0
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- carpet 1.4.83
	- carpet-fixes 1.19-1.11.2
	- charmonium 4.2.1
	- chat-up 2.1
	- citresewn 1.1.1+1.19
	- citresewn-defaults 1.1.1+1.19 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73 via bedrockify
	- com_electronwill_night-config_core 3.6.2 via charmonium
	- com_electronwill_night-config_toml 3.6.2 via charmonium
	- com_github_llamalad7_mixinextras 0.1.1 via adaptive-tooltips
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charmonium
	- com_typesafe_config 1.4.2 via bobby
	- conditional-mixin 0.3.0 via carpet-fixes
	- continuity 2.0.1+1.19
	- crowdin-translate 1.4+1.19 via antighost
	- ctrl-q 1.8
	- cull-less-leaves 1.0.4
	- dark-loading-screen 1.6.12
	- disableinsecurechattoast 1.1.0
	- disablemessagedeletion 1.0.1
	- emojitype 2.0.1+1.19
	- enhancedblockentities 0.7.1+1.19
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.5.2-mc1.19
	- exordium 1.0.1-mc1.19.2
	- extrasounds 2.3.1+1.19.2-1.19.1
	- fabric 0.58.5+1.19.1
	- fabric-api-base 0.4.12+93d8cb8290 via nochatreports
	- fabric-api-lookup-api-v1 1.6.7+9ff28f4095 via fabric
	- fabric-biome-api-v1 9.0.15+d5533c0195 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f4095 via fabric
	- fabric-command-api-v1 1.2.9+f71b366f95 via fabric
	- fabric-command-api-v2 2.1.5+0c17ea9695 via fabric
	- fabric-commands-v0 0.2.26+df3654b395 via fabric
	- fabric-containers-v0 0.1.31+df3654b395 via fabric
	- fabric-content-registries-v0 3.2.1+07df213e95 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d2495 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4a95 via fabric
	- fabric-data-generation-api-v1 5.1.5+a680b9b495 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f78595 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f4095 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f4095 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b395 via fabric
	- fabric-game-rule-api-v1 1.0.19+1899036195 via fabric
	- fabric-item-api-v1 1.5.5+35a03c4395 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f4095 via fabric
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via iris
	- fabric-keybindings-v0 0.2.16+df3654b395 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc73895 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e56895 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c695 via fabric
	- fabric-message-api-v1 5.0.1+4e0178f495 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc73895 via fabric
	- fabric-models-v0 0.3.15+9ff28f4095 via fabric
	- fabric-networking-api-v1 1.2.5+c6af733c90 via nochatreports
	- fabric-networking-v0 0.3.18+df3654b395 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f4095 via fabric
	- fabric-particles-v1 1.0.8+dc39553a95 via fabric
	- fabric-registry-sync-v0 0.9.21+23c4cfef95 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f4095 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39f95 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b395 via fabric
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via sodium
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via sodium
	- fabric-rendering-v0 1.1.20+df3654b395 via fabric
	- fabric-rendering-v1 1.11.0+73145abb90 via nochatreports
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a395 via fabric
	- fabric-resource-loader-v0 0.7.2+70efcffe90 via nochatreports
	- fabric-screen-api-v1 1.0.27+93d8cb8290 via nochatreports
	- fabric-screen-handler-api-v1 1.2.10+9ff28f4095 via fabric
	- fabric-textures-v0 1.0.18+9ff28f4095 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a395 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c695 via fabric
	- fabricloader 0.14.10
	- fallingleaves 1.12.1+1.19
	- faster_entity_animations 1.5.6
	- ferritecore 4.2.1
	- forcecloseloadingscreen 1.1.1
	- fpsreducer 1.19-2.0.2
	- idwtialsimmoedm 0.1.2+1.19
	- indium 1.0.9+mc1.19.2
	- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.4.2
	- java 17
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- lithium 0.9.0
	- logical_zoom 0.0.17
	- memoryleakfix 1.19.1-0.7.0
	- minecraft 1.19.2
	- minecraftcapes 12.1.0
	- modmenu 4.0.6
	- nightvision 1.0.1
	- nochatreports 1.19.2-v1.13.11
	- notenoughanimations 1.6.2
	- notenoughcrashes 4.1.6+1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- organizableplayscreens 1.0.2
	- pride 1.1.2+1.19 via lambdynlights
	- rainbowify 2.0.0-alpha.3
	- raised 1.1.3
	- reeses-sodium-options 1.4.5+mc1.19.2-build.51
	- searchablecontainers 2.0.2+mc1.19
	- shulkerboxtooltip 3.1.1+1.19
	- skinlayers 1.5.1-mc1.19.1
	- smoothboot 1.19-1.7.1
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.13+mc1.19.2-build.76
	- sound_physics_remastered 1.19.2-1.0.16
	- soundcategories 1.2.4+1.19 via extrasounds
	- spruceui 4.0.0+1.19 via enhancedblockentities
	- starlight 1.1.1+fabric.ae22326
	- suggestion_tweaker 1.19.1-1.3.1
	- tcdcommons 1.0+1.19.2 via betterstats
	- voicechat 1.19.2-2.3.6
	- waveycapes 1.2.1
	- wmch 1.5.3
	- xaerominimapfair 22.13.2
	- xaeroworldmap 1.26.2
	- yet-another-config-lib 1.7.1
[10:18:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/aiden/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:18:38] [main/INFO]: Compatibility level set to JAVA_17
[10:18:38] [main/INFO]: OptiFine was NOT detected.
[10:18:38] [main/INFO]: OptiFabric was NOT detected.
[10:18:38] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 1 override(s) found
[10:18:38] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[10:18:38] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[10:18:39] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/gui/widget/basewidgets/LabelWidget (java.lang.ClassNotFoundException: me/shedaniel/rei/impl/client/gui/widget/basewidgets/LabelWidget)
[10:18:39] [main/INFO]: Disabling ModelUtilMixin as MemoryLeakFix is loaded.
[10:18:39] [main/INFO]: bre2el.fpsreducer.mixin.MinecraftClientMixin will be applied.
[10:18:39] [main/INFO]: bre2el.fpsreducer.mixin.KeyboardMixin will be applied.
[10:18:39] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[10:18:39] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[10:18:39] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[10:18:39] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD)
[10:18:39] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.structureMovement.interaction.controls.TrainHUD was not found raised.mixins.json:mods.CreateMixin$ToolboxHandlerClientMixin from mod raised
[10:18:39] [main/WARN]: Error loading class: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient (java.lang.ClassNotFoundException: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient)
[10:18:39] [main/WARN]: @Mixin target com.simibubi.create.content.curiosities.toolbox.ToolboxHandlerClient was not found raised.mixins.json:mods.CreateMixin$TrainHUDMixin from mod raised
[10:18:39] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[10:18:40] [main/INFO]: I used the json to destroy the json
[10:18:40] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adaptive-tooltips'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adaptive-tooltips'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: java.lang.LinkageError: loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @80ec1f8 attempted duplicate class definition for com.llamalad7.mixinextras.MixinExtrasBootstrap. (com.llamalad7.mixinextras.MixinExtrasBootstrap is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @80ec1f8, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @5606c0b)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
```

**Comment by HoodieRocks** [comment]
Updating fabric-api did not fix the issue

**Comment by HoodieRocks** [comment]
After removing the mod, my game continued to crash, finding out it was MemoryLeakFix, although this did not fix the crashing

**Comment by isXander** [comment]
This is indeed a Fabric Loader problem. You can do a few things:
1. Show support on the open [pull request](https://github.com/FabricMC/fabric-loader/pull/733) on the fabric loader repository, which fixes this issue.
2. Switch to [Quilt Loader](https://quiltmc.org), which fixed this issue months ago. This would involve swapping Fabric API to QSL. *all fabric mods still work!*
